[package]
authors = ["BitByteLab Developers <dev.team@bitbytelab.io>"]
edition = "2021"
name = "tradingview-rs"
version = "0.0.1"
license = "MIT"
repository = "https://github.com/bitbytelabio/tradingview-rs"
readme = "README.md"
description = "Tradingview datafeed `tradingview-rs` project."

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
