[package]
name = "tradingview-rs"
authors = ["Bit Byte Lab Developers <dev.team@bitbytelab.io>"]
version = "0.0.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/bitbytelabio/tradingview-rs"
readme = "README.md"
description = "Tradingview datafeed api `tradingview-rs` project."

[dependencies]
tokio = { version = "^1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1.0" }
reqwest = { version = "0.11", features = [
    "rustls-tls",
    "json",
    "blocking",
    "gzip",
    "deflate",
    "cookies",
    "multipart",
] }
lazy_static = "^1.4"
url = "^2"
rand = "^0.8"
regex = "^1"
google-authenticator = "^0.4"
tokio-tungstenite = { version = "^0.20", features = [
    "rustls-tls-native-roots",
] }
futures-util = { version = "0.3", default-features = false, features = [
    "sink",
    "std",
] }
futures-channel = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
thiserror = "^1.0"
async-trait = "^0.1"

# rayon = { version = "1.7" }
# log = "0.4"
# env_logger = "0.10"
# http = "^0.2"


[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[example]]
name = "auth"

[[example]]
name = "websocket"

[[example]]
name = "utils"
