name: Example workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: hello action
        run: echo "Hello Actions"
        shell: bash
