name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Unit test
        run: make test
        shell: bash
