name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  HOME: /home/action

jobs:
  build_and_test:
    runs-on: self-hosted
    steps:
      - run: sudo apt install -y pkg-config libssl-dev
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
        env:
          TV_SESSION: ${{ secrets.TV_SESSION }}
          TV_SIGNATURE: ${{ secrets.TV_SIGNATURE }}
          TV_USERNAME: ${{ secrets.TV_USERNAME }}
          TV_PASSWORD: ${{ secrets.TV_PASSWORD }}
          TV_TOTP_USERNAME: ${{ secrets.TV_TOTP_USERNAME }}
          TV_TOTP_PASSWORD: ${{ secrets.TV_TOTP_PASSWORD }}
          TV_TOTP_SECRET: ${{ secrets.TV_TOTP_SECRET }}
